### ISSUE TITLE
Allow detection of support with @media / @supports

### ISSUE THREAD

**Issue by metaa** [WICG/open-ui#68]
I believe it would be a great addition if we were able to detect the availibility of the refreshed control styles via [@supports](https://developer.mozilla.org/docs/Web/CSS/@supports).

This way CSS can be adapted to work for browsers that do or do not use/support the new styles, or at a point of time before broader support it would signal if the feature flag was enabled or not.

Otherwise making use of new styling rules may impact the look on older browsers or those who do not have the feature flag enabled.

**Comment by levithomason** [comment]
Hi @metaa, thanks for the post.  Could you give a use case or example?  I'm struggling a bit to understand.  Specifically, I'm not sure what you mean by "the new styles" and "new styling rules" mentioned.

For context, there are two groups of folks here in Open UI, browser platform representatives and those from design systems/frameworks.  I'm coming from the the design/framework side.

**Comment by metaa** [comment]
Hi @levithomason, thanks for your relpy.

I really hope I'm in the right place for this. I came here because of [the blog](https://blog.chromium.org/2020/03/updates-to-form-controls-and-focus.html) post that pointed out changes to the HTML input controls.

I would like to be able to detect support of those styles in the browser so the browser would use the correct styles for the controls.

# Problem and workaround
Let's take this meter element for example:
```html
<meter value="50" max="100"></meter>
```
![image](https://user-images.githubusercontent.com/5056880/79053607-fa74da00-7c3e-11ea-8a36-b99f7efcbb9f.png)

Right now I would need this piece of CSS to make it red:

```css
meter::-webkit-meter-optimum-value {
    background: red;
}
```

It would then be red, but lose the gradient on the colored section:
![image](https://user-images.githubusercontent.com/5056880/79053632-21331080-7c3f-11ea-93c5-08e6f693c698.png)

Now for additional styling, I might have to add an HTML container to apply more styles like a `::before` block that covers the meter or something just to make it look right.

```html
<div class="meter-styler">
    <meter value="50" max="100"></meter>
</div>
```
```css
.meter-styler {
    position: relative;
    display: inline-block;
}
.meter-styler meter::-webkit-meter-optimum-value {
    background: red;
}
.meter-styler::after {
    content: '';

    position: absolute;
    top: 0;
    left: 0;

    width: 50%;
    height: 100%;

    background: linear-gradient(to bottom, white, transparent 70%);
}
```
![image](https://user-images.githubusercontent.com/5056880/79053738-c51cbc00-7c3f-11ea-84f5-6d5f7d726d4c.png)

(Let's ignore the fact that the `filter` rule exists for a moment 😄)

---

With the proposed refresher from the Open UI working group, this CSS might (it doesn't work, but it might in the future? 🤷‍♂️) boil down to this in order to make a nice red bar.

```html
<meter value="50" max="100"></meter>
```
```css
meter {
    color: red
}
```
![image](https://user-images.githubusercontent.com/5056880/79053755-e2ea2100-7c3f-11ea-8746-1bf71d0eb75e.png)

(for this screenshot I actually used `filter: hue-rotate(240deg) saturate(20)`)

# A possible solution
Since styling of the control elements might be easier after the refresher, I would not have to do additional stuff like overlaying elements or applying filters etc.

For this case one could use something like a simple `@media` block.

```html
<meter value="50" max="100"></meter>
```
```css
/* new */
@media (uses-refreshed-2020-controls) {
    .meter-styler meter {
        color: red
    }
}

/* old */
@media not (uses-refreshed-2020-controls) {
    .meter-styler {
        position: relative;
        display: inline-block;
    }
    .meter-styler meter::-webkit-meter-optimum-value {
        background: red;
    }
    .meter-styler::after {
        content: '';
        
        position: absolute;
        top: 0;
        left: 0;
        
        width: 50%;
        height: 100%;
        
        background: linear-gradient(to bottom, white, transparent 70%);
    }
}
```

## Result
### Old browser / flag disabled
![image](https://user-images.githubusercontent.com/5056880/79053738-c51cbc00-7c3f-11ea-84f5-6d5f7d726d4c.png)

### New browser / flag enabled
![image](https://user-images.githubusercontent.com/5056880/79053755-e2ea2100-7c3f-11ea-8746-1bf71d0eb75e.png)

---

If there's anything I'm missing, please tell me 😅
